language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION=">=1.10,<1.11"
  - DJANGO_VERSION=">=1.11,<1.12"
install:
  - pip install Django$DJANGO_VERSION
  - pip install -r requirements-test.txt
  - pip install codecov
script: PYTHONPATH=. DJANGO_SETTINGS_MODULE=django_otp_u2f.tests.settings coverage run --source=django_otp_u2f `which django-admin.py` test
after_success:
  - codecov
